lists/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Thejojo'

from django.conf.urls import url,include
from lists.views import view_list
from lists.views import new_list
from lists.views import register
from lists.views import userinfo
from lists import views as lists_views

urlpatterns = [
    url(r'^(\d+)/$', view_list, name="view_list"),
    url(r'^new$', new_list, name="new_list"),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^accounts/register',register, name="register"),
    url(r'^accounts/userinfo',userinfo, name="userinfo"),


]

python_ToDo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from lists.views import home_page
from lists.views import view_list
from lists.views import new_list
from lists import views as lists_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', home_page, name="home"),
    url(r'^lists/',include('lists.urls',namespace="lists")),

    # url(r'^lists/(\d+)/$', view_list, name="view_list"),
    # url(r'^lists/(\d+)/add_item$', add_item, name="add_item"),
    # url(r'^lists/new$', new_list, name="new_list"),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User

# Create your models here.

class UserInfo(models.Model):
    # 一对一，一条信息，对应一个人
    # related_name是反向关联
    belong_to = models.OneToOneField(to=User, related_name='info')

    # 添加要扩展到 User 中的新字段
    age = models.IntegerField("年龄",null=True, blank=True)
    address = models.CharField("地址",max_length=50, null=True, blank=True)

    def __str__(self):
        return self.belong_to

class List(models.Model):

    def get_absolute_url(self):
        return reverse('lists:view_list',args=[self.id])

class Item(models.Model):
    text = models.TextField(max_length=100, default="")
    list = models.ForeignKey(List, default=None)

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')


    def __str__(self):
        return self.text

lists/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

__author__ = 'Thejojo'


from django import forms
from lists.models import Item
from django.core.exceptions import ValidationError

EMPTY_LIST_ERROR = "You can't have an empty list item"
DUPLICATE_ITEM_ERROR = "You've already got this in your list"

class ItemForm(forms.models.ModelForm):

    class Meta:
        model = Item
        fields = ('text',)
        widgets = {
            'text' : forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
                'class': 'form-control input-lg',
        }),
        }
        error_messages = {
            'text' : {'required': EMPTY_LIST_ERROR }
        }

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()



class ExistingListItemForm(ItemForm):

    def __init__(self, for_list, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.instance.list = for_list


    def validate_unique(self):
        try:
            self.instance.validate_unique()
        except ValidationError as e:
            e.error_dict = {'text': [DUPLICATE_ITEM_ERROR]}
            self._update_errors(e)



    def save(self):
        return forms.models.ModelForm.save(self)

lists/views.py
from django.shortcuts import render,redirect
from lists.models import Item,List
from django.core.exceptions import ValidationError
from lists.forms import ItemForm,ExistingListItemForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login,authenticate
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
# Create your views here.

# 用户信息


def userinfo(request):
    return render(request, 'registration/userinfo.html')


# 注册函数
def register(request):
    context = {}
    if request.method == 'GET':
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            username = request.POST['username']
            password = request.POST['password1']
            user = authenticate(username=username, password=password)
            login(request,user)
            # return HttpResponseRedirect('/')
            return HttpResponseRedirect(reverse('home'))

            # return redirect(to='home')
        # else:
        #     return  HttpResponseRedirect('/lists/accounts/register',form.errors)

    context['form'] = form
    return render(request, 'registration/register.html', context)


# 登陆函数




def home_page(request):
    # return HttpResponse('<html><title>To-Do lists</title></html>')
    # if request.method == "POST":
    #     return HttpResponse(request.POST['item_text'])
    return render(request, 'home.html',{'form': ItemForm()}
    )

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ExistingListItemForm(for_list=list_)
    # items = Item.objects.filter(list=list_)
    if request.method == 'POST':

        form = ExistingListItemForm(for_list=list_,data=request.POST)
        if form.is_valid():
            form.save()
            # Item.objects.create(text = request.POST['text'],list=list_)

            return redirect(list_)
    return render(request, 'list.html',{'list':list_, 'form':form}
    )


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})

    # return redirect('lists:view_list' ,list_.id)

lists/templates/base.html
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <title>{% block title %}{% endblock %}</title>

    <link href="/static/base.css" rel="stylesheet" media="screen">
    <!-- Bootstrap -->
    {#    <link href="css/bootstrap.min.css" rel="stylesheet">#}
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
      <link href="/static/base.css" rel="stylesheet">
    <![endif]-->


</head>
<body>

{% block navabar %}
    {% include "navbar.html"%}
{% endblock %}


<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
            <div class="text-center">

                <h1>{% block header_text %}{% endblock %}</h1>
                {% block content %} {% endblock %}
                {% block todos %}
                <form method="POST" action="{% block form_action %}{% endblock %}">

                    {{ form.text }}
                    {#    <p style="text-align: center;">#}
                    {#                    <input name="item_text" id="id_new_item" class="form-control input-lg"#}
                    {#                           placeholder="Enter a to-do item">#}
                    {#    </p>#}
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="form-group has-error">
                            <div class="help-block ">
                                {{ form.text.errors }}
                            </div>
                        </div>

                    {% endif %}
                </form>
                {% endblock %}


            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            {% block table %}
            {% endblock %}

        </div>
    </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    {#    <script src="js/bootstrap.min.js"></script>#}
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
            crossorigin="anonymous"></script>

</div>


</body>
</html>

lists/templates/home.html
{% extends 'base.html' %}
    {% block title %}To-Do lists Home Page{% endblock %}

{% block header_text %}Your To-Do Home Page{% endblock %}

{% block form_action %}{% url 'lists:new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}
    {% block title %}To-Do lists{% endblock %}

{% block header_text %}Your To-Do List Page{% endblock %}

{% block form_action %}{% url 'lists:view_list' list.id %}{% endblock %}

{% block table %}
<table id="id_list_table" class="table">
    {% for item in list.item_set.all %}
        <tr>
            <td>{{ forloop.counter }}: {{ item.text }}</td>
        </tr>
    {% endfor %}
</table>
{% endblock %}

lists/templates/navbar.html
<nav class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{% url 'home' %}" class="navbar-brand">Home Page</a>
    </div>




    <div id="navbar" class="collapse navbar-collapse bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="/admin">Admin Page</a></li>
      </ul>



      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'lists:userinfo' %}" title="个人信息"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> {{ user.username }}</a>
        </li>
        <li>
        <a href="{% url 'lists:logout' %}" title="退出">退出    <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span></a>
        </li>



        {% else %}

        <li class="sign-in-up"><a href="{% url 'lists:register' %}">注册 <span class="sr-only"></span></a></li>

            <li class="sign-in-up"><a href="{% url 'lists:login' %}">登陆 <span class="sr-only"></span></a></li>

{#        <li>#}
{#        <div class="active">#}
{#          <a href="{% url 'home' %}?next={{ request.path  }}" class="btn">注册</a>#}
{#        </div>#}
{#        </li>#}
{#        <li>#}
{#        <div class="sign-in-up">#}
{#          <a href="{% url 'home' %}?next={{ request.path  }}" class="btn">登录</a>#}
{#        </div>#}
{#        </li>#}
        {% endif %}
      </ul>
    </div>
  </div>
</nav>